# -*- yaml -*-
language: python
python:
  - "2.7"
env:
  global:
    - PATH=$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin
install:
  - npm install less coffee-script
  - pip install .
  - env
  - which -a lessc coffee
services:
  - rabbitmq
script:
  - make actual-test
