language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - flake8 --ignore=E221,E701,E202,E123 freezr systemtests
services:
  - rabbitmq
script:
  - python manage.py test -v2
  - ./systemtests/run-fake-integration-test.sh
