#!/bin/bash -e
top_dir=$(dirname $0)
cfn=$top_dir/testnetworks.cfn.json
cfn_temp=$top_dir/testnetworks.cfn.filtered.json
stack=${1-freezr-test}
egrep -v '^[ 	]*//' $cfn >$cfn_temp

function running {
    aws cloudformation describe-stacks --stack-name $stack >/dev/null 2>&1 </dev/null
    return $?
}

if ! aws cloudformation validate-template --template-body file://$cfn_temp; then
    echo "ERROR: Template validation failed, processed file in $(basename $cfn_temp) file." >&2
    exit 1
fi

if running; then
    echo -n 'Stack running, deleting and waiting to terminate '
    aws cloudformation delete-stack --stack-name $stack
    while running
    do
	echo -n "."
	sleep 1
    done
    echo " done"
fi
aws cloudformation create-stack --stack-name $stack --parameters 'ParameterKey=KeyName,ParameterValue=freezr' --template-body file://$cfn_temp
exit 0
